### ISSUE TITLE
web_search_agent_streamlit.py NameError: name 'model' is not defined

### ISSUE THREAD

**Issue by mberth** [coleam00/ai-agents-masterclass#26]
The streamlit version of the web search agent (Pydantic AI) is broken:

```sh
$ cd ai-agents-masterclass/pydantic-ai
$ python web_search_agent_streamlit.py
Traceback (most recent call last):
  File "/.../ai-agents-masterclass/pydantic-ai/web_search_agent_streamlit.py", line 24, in <module>
    model,
    ^^^^^
NameError: name 'model' is not defined
```

**Comment by aalstes** [comment]
I got the same error. Readme is wrong.
I had to run:
streamlit run streamlit_ui.py

**Comment by coleam00** [comment]
I updated the README @aalstes, thank you for pointing that out! And thanks for opening this issue @mberth!

**Comment by aalstes** [comment]
And thank you for your amazing YouTube content! Best channel I know about for learning about AI agents.
